// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetScoreboard() {
  return window['go']['main']['App']['GetScoreboard']();
}

export function SaveScoreboardJSON(arg1) {
  return window['go']['main']['App']['SaveScoreboardJSON'](arg1);
}

export function UpdateScoreboard(arg1) {
  return window['go']['main']['App']['UpdateScoreboard'](arg1);
}
