// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetBracket():Promise<main.Bracket>;

export function GetCommentary():Promise<main.Commentary>;

export function GetScoreboard():Promise<main.Scoreboard>;

export function SaveBracketJSON(arg1:main.Bracket):Promise<void>;

export function SaveCommentaryJSON(arg1:main.Commentary):Promise<void>;

export function SaveScoreboardJSON(arg1:main.Scoreboard):Promise<void>;
