// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteSponsor(arg1:string):Promise<void>;

export function GetBracket():Promise<main.Bracket>;

export function GetCommentary():Promise<main.Commentary>;

export function GetScoreboard():Promise<main.Scoreboard>;

export function GetSponsorList():Promise<Array<string>>;

export function GetSponsors():Promise<Array<string>>;

export function LoadPlayersCSV():Promise<Array<Record<string, string>>>;

export function SaveBracketJSON(arg1:main.Bracket):Promise<void>;

export function SaveCommentaryJSON(arg1:Record<string, any>):Promise<void>;

export function SavePlayersCSV(arg1:Array<Record<string, string>>):Promise<void>;

export function SaveScoreboardJSON(arg1:main.Scoreboard):Promise<void>;

export function SaveSponsor(arg1:string,arg2:Array<number>):Promise<void>;

export function UploadSponsor(arg1:string,arg2:Array<number>):Promise<void>;
