// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBracket() {
  return window['go']['main']['App']['GetBracket']();
}

export function GetCommentary() {
  return window['go']['main']['App']['GetCommentary']();
}

export function GetScoreboard() {
  return window['go']['main']['App']['GetScoreboard']();
}

export function SaveBracketJSON(arg1) {
  return window['go']['main']['App']['SaveBracketJSON'](arg1);
}

export function SaveCommentaryJSON(arg1) {
  return window['go']['main']['App']['SaveCommentaryJSON'](arg1);
}

export function SaveScoreboardJSON(arg1) {
  return window['go']['main']['App']['SaveScoreboardJSON'](arg1);
}
